services:

  discord-bot:

    build: .

    container_name: bot-discord-v6

    restart: unless-stopped

    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      WELCOME_CHANNEL_ID: ${WELCOME_CHANNEL_ID}